# Generated by Django 5.1.15 on 2026-08-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('bodeguero', 'Jefe de Bodega'), ('operario', 'Operario')], default='operario', help_text='Define el perfil de acceso y permisos dentro del sistema.', max_length=20, verbose_name='Rol'),
        ),
    ]
